# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  default:
    docker:
      - image: namachan10777/namachan10777.dev:latest
        environment:
          RUST_LOG: Info
  nodejs:
    docker:
      - image: public.ecr.aws/lambda/nodejs:12

jobs:
  test_js:
    executor: nodejs
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm ci
      - run:
          name: format
          command: npm run fmt-check 
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-test-{{ checksum "engine/Cargo.lock" }}
      - run:
          name: Test engine
          command: cd engine && cargo test
      - run:
          name: Clippy
          command: cd engine && cargo clippy -- -D warnings
      - run:
          name: Cargo fmt
          command: cd engine && cargo fmt -- --check
      - save_cache:
          key: v3-test-{{ checksum "engine/Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - engine/target

  build_engine:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-build-{{ checksum "engine/Cargo.lock" }}
      - run:
          name: Build engine
          command: |
            cd engine
            cargo build --release
      - run:
          name: save
          command: |
            mkdir -p workspace
            cp engine/target/release/engine workspace/engine
      - persist_to_workspace:
          root: workspace
          paths:
            - engine
      - save_cache:
          key: v3-build-{{ checksum "engine/Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - engine/target

  build:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build pages
          command: |
            /tmp/workspace/engine ./public/ public.zip
      - run:
          name: Deploy
          command: |
            curl -H 'User-Agent: namachan10777 (namachan10777@gmail.com)' \
                 -H 'Authorization: Bearer ${NETLIFY_TOKEN}' \
                 https://api.netlify.com/api/v1/sites

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - test_js:
          filters:
            branches:
              only: [next, parse-md]
      - build_engine:
          filters:
            branches:
              ignore: [deploy, next, parse-md]
      - test:
          filters:
            branches:
              ignore: [deploy, next, parse-md]
      - build:
          requires:
            - build_engine
            - test
          filters:
            branches:
              only:
                - master
