# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  nodejs:
    docker:
      - image: public.ecr.aws/lambda/nodejs:12

jobs:
  test_js:
    executor: nodejs
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm ci
      - run:
          name: format
          command: npm run fmt-check 
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  test:
    jobs:
      - test_js