# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  default:
    docker:
      - image: namachan10777/namachan10777.dev:latest

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir dist
            make
      - run:
          name: Deploy to netlify
          command: |
            git config user.email "namachan10777@gmail.com"
            git config user.name "Nakano Masaki"
            git add dist/* -f
            git commit -m "auto commit"
            git checkout -b production
            git push origin production -f

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
