# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  default:
    working_directory: ~/
    docker:
      - image: namachan10777/namachan10777.dev:latest

jobs:
  build:
    executor:
      name: default
    steps:
      - run:
          name: Deploy to netlify
          command: netlify deploy --prod -d . -a ${NETLIFY_TOKEN} -s ${NETLIFY_SITE_ID}
