# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  default:
    docker:
      - image: namachan10777/namachan10777.dev:latest

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Build
          command: |
            /usr/local/bin/engine -c public/config.json -d public.zip

      - run:
          name: Deploy to netlify
          command: |
            curl -XPOST \
              -H 'Content-Type: application/zip' \
              -H 'Authorization: Bearer '$NETLIFY_TOKEN \
              --data-binary @public.zip \
              https://api.netlify.com/api/v1/sites/namachan10777.netlify.com/deploys

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
