[package]
name = "unmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-recursion = "1.0.4"
async-trait = "0.1.68"
axohtml = "0.5.0"
axum = { version = "0.6.17", features = ["headers"] }
chrono = "0.4.24"
clap = { version = "4.0.32", features = ["derive"] }
comrak = {version="0.18.0", features = [], default-features=false}
image = {version="0.24.6", features = ["jpeg", "gif", "ico", "png", "tga", "tiff", "webp", "webp-encoder"], default-features=false}
infer = "0.13.0"
itertools = "0.10.5"
liquid = "0.26.1"
maplit = "1.0.2"
mime = "0.3.17"
nom = "7.1.3"
notify = "5.1.0"
once_cell = "1.17.1"
regex = "1.8.1"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.16"
syntect = "5.0.0"
thiserror = "1.0.38"
tokio = { version = "1.24.1", features = ["net", "rt-multi-thread", "macros", "fs", "signal", "tracing", "io-util", "sync"] }
tokio-stream = {version="0.1.12", features = ["fs"]}
toml = "0.5.10"
tracing = { version = "0.1.37", features = ["valuable"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
