[package]
name = "unmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
pulldown-cmark = "0.9.2"
thiserror = "1.0.38"
tokio = { version = "1.24.1", features = ["net", "rt-multi-thread", "macros", "fs", "signal", "tracing"] }
tracing = { version = "0.1.37", features = ["valuable"] }
