import React from "react";
import Head from "next/head";
import Md from "../components/md";
import readme from "../articles/nextjs-blog.md";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkFrontmatter from "remark-frontmatter";
import * as MdAst from "mdast";

export const config = { amp: true };

type Props = {
  mdast: MdAst.Root;
};

export default function Home(props: Props) {
  console.log(props.mdast);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Md mdast={props.mdast} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const md = unified()
    .use(remarkParse)
    .use(remarkFrontmatter, ["toml", "yaml"])
    .use(remarkGfm)
    .parse(readme);
  return {
    props: { mdast: md },
  };
}
