# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: HTML deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.8
    - uses: actions/checkout@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    - run: |
        earthly \
          --secret CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          --secret CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          --remote-cache=ghcr.io/namachan10777/namachan10777-dev:cache \
          --push \
          +deploy --PROJECT_NAME=${{ secrets.CF_PROJECT_NAME }}
