# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          .yarn
        key: node-v1-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.23.6
    - run: npm i -g pnpm
    - run: pnpm install
    - run: pnpm run check-format
    - run: pnpm run build
    - run: test -z "$(git diff)"
